name: flutter_movieseriestracker
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  mongo_dart: ^0.10.4
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/series/911.jpg
    - assets/series/Friends.jpg
    - assets/series/AmericanIdol.jpg
    - assets/series/AttackOnTitan.jpg
    - assets/series/BreakingBad.jpg
    - assets/series/GameOfThrones.jpg
    - assets/series/GreysAnatomy.jpg
    - assets/series/ItaewonClass.jpg
    - assets/series/SquidGame.jpg
    - assets/series/TheMaskedSinger.jpg
    - assets/series/TheStrangerThings.jpg
    - assets/series/Vincenzo.jpg
    - assets/series/XoKitty.jpg
    - assets/movies/Avatar2.jpg
    - assets/movies/Barbie.jpg
    - assets/movies/Frozen3.jpg
    - assets/movies/HowToTrainYourDragon.jpg
    - assets/movies/KarateKid_Legends.jpg
    - assets/movies/MortalKombat.jpg
    - assets/movies/Mulan.jpg
    - assets/movies/RayaAndTheLastDragon.jpg
    - assets/movies/Smile2.jpg
    - assets/movies/TheBatmanPart2.jpg
    - assets/movies/TheCall.jpg
    - assets/movies/TheLittleMermaid.jpg
    - assets/movies/TheMonkey.jpg
    - assets/movies/TheNun2.jpg
    - assets/movies/TheStrays.jpg
    - assets/movies/TurningRed.jpg
    - assets/movies/WakandaForever.jpg
    - assets/movies/Zootopia2.jpg
    - assets/logo/tvmate_logo_s.png
    - assets/logo/tvmate_logo_m.png